version: '3.3'
services:
  transmission:
    image: "haugene/transmission-openvpn:latest"
    env_file:
      - transmission.env
    volumes:
      - /tmp/transmission/config:/config
      - /tmp/transmission/data:/data
      - /tmp/transmission/downloads:/downloads
    privileged: true
    expose:
      - "9091"
    ports:
      - "9091:9091"
  jackett:
    image: "linuxserver/jackett:latest"
    volumes:
      - /tmp/jackett/config:/config
      - /tmp/jackett/downloads:/downloads
    expose:
      - "9117"
    ports:
      - "9117:9117"
  sonarr:
    image: "linuxserver/sonarr:latest"
    volumes:
      - /tmp/transmission/downloads:/downloads
      - /tmp/sonarr/config:/config
      - /tmp/media/tv:/tv
    ports:
      - "8989:8989"
  couchpotato:
    image: "linuxserver/couchpotato:latest"
    volumes:
      - /tmp/couch/config:/config
      - /tmp/transmission/downloads:/downloads
      - /tmp/media/movies:/movies
    ports:
      - "10004:5050"
