version: '3.3'
services:
  transmission:
    image: "haugene/transmission-openvpn:latest"
    env_file:
      - transmission.env
    volumes:
      - /share/CACHEDEV1_DATA/Docker/transmission/config:/config
      - /share/CACHEDEV1_DATA/Docker/transmission/data:/data
    privileged: true
    network_mode: "host"
  jackett:
    image: "linuxserver/jackett:latest"
    volumes:
      - /share/CACHEDEV1_DATA/Docker/jackett/config:/config
      - /share/CACHEDEV1_DATA/Docker/jackett/downloads:/downloads
    network_mode: "host"
  sonarr:
    image: "linuxserver/sonarr:latest"
    volumes:
      - /share/CACHEDEV1_DATA/Docker/transmission/data/completed:/downloads
      - /share/CACHEDEV1_DATA/Docker/sonarr/config:/config
      - /share/CACHEDEV1_DATA/Multimedia/tv:/tv
    network_mode: "host"
  radarr:
    image: "linuxserver/radarr:latest"
    volumes:
      - /share/CACHEDEV1_DATA/Docker/radarr/config:/config
      - /share/CACHEDEV1_DATA/Docker/transmission/data/completed/:/downloads
      - /share/CACHEDEV1_DATA/Multimedia/movies:/movies
    network_mode: "host"
  lidarr:
    image: "linuxserver/lidarr:latest"
    volumes:
      - /share/CACHEDEV1_DATA/Docker/lidarr/config:/config
      - /share/CACHEDEV1_DATA/Docker/transmission/data/completed/:/downloads
      - /share/CACHEDEV1_DATA/Multimedia/music:/music
    network_mode: "host"
